"""twingraph — the typed, executable, versioned decision-twin IR.

Open-source core (Apache-2.0). Carries no proprietary dependencies (stdlib +
pydantic only) and is designed to be embedded by application runtimes that own
models, data connectors, optimizers, and serving infrastructure.
"""

from .canonical import (
    HASH_EXCLUDED_FIELDS,
    SCHEMA_VERSION,
    canonical_json,
    canonicalize,
    content_hash,
)
from .compile import (
    COMPILER_VERSION,
    CompileReport,
    CompileResult,
    CompiledConstraint,
    ExecutablePlan,
    ProgramCompatibilityReport,
    QueryPlan,
    ResolvedComponent,
    ResolvedObjective,
    compile_graph,
)
from .compose import CompositionReport, compose
from .document import SENTINEL_WORKSPACE, TwinGraph
from .errors import (
    CODES,
    CompositionError,
    Diagnostic,
    FrozenGraphError,
    ImmutableGraphError,
    OutOfOrderPatchError,
    TwinGraphError,
    UnknownModelRefError,
    UnknownTypeRefError,
)
from .ids import Ulid, new_ulid, validate_ulid
from .patch import (
    Operation,
    PatchApplyReport,
    PatchLog,
    PatchStatus,
    SemanticPatch,
    apply_patch,
    lineage,
)
from .primitives import (
    EXECUTABLE_MODEL_KINDS,
    FOREIGN_MODEL_KINDS,
    RELATION_TYPE_REF_PATTERN,
    Action,
    ActionBound,
    ConfirmationState,
    Constraint,
    ConstraintEvaluator,
    ConstraintExpression,
    DataBinding,
    Entity,
    EntityPort,
    Evidence,
    LifecycleState,
    ModelBinding,
    ModelBindingKind,
    Objective,
    ObjectiveAggregation,
    ObjectiveTerm,
    Provenance,
    Relation,
    RelationType,
    Validator,
    ValidatorResult,
    Variable,
)
from .programs import (
    BUILTIN_PROGRAM_REGISTRY,
    InMemoryProgramRegistry,
    ProfileRequirement,
    ProgramProfile,
    ProgramRegistry,
)
from .registry import (
    BUILTIN_TYPE_REGISTRY,
    BUILTIN_TYPE_PACKS,
    DATA_TYPE_PACK,
    DATA_CENTER_TYPE_PACK,
    OPERATIONS_TYPE_PACK,
    PLATFORM_ANALYSIS_TYPE_PACK,
    POWER_TYPE_PACK,
    RELATION_TYPE_PACK,
    ActionSpec,
    IOContract,
    InMemoryTypeRegistry,
    ModelRegistry,
    ModelSpec,
    PropSpec,
    TypeDef,
    TypePack,
    TypeRegistry,
    VarSpec,
    build_type_registry,
    register_type_pack,
)
from .units import (
    DEFAULT_UNIT_REGISTRY,
    Quantity,
    UnitRegistry,
    normalize_unit,
    units_compatible,
)
from .viz import to_dot, to_mermaid

__version__ = "0.3.0"

__all__ = [
    "__version__",
    "SCHEMA_VERSION",
    "HASH_EXCLUDED_FIELDS",
    "canonical_json",
    "content_hash",
    "canonicalize",
    # primitives
    "Entity",
    "EntityPort",
    "Relation",
    "Variable",
    "DataBinding",
    "ModelBinding",
    "Action",
    "ActionBound",
    "Constraint",
    "ConstraintExpression",
    "ConstraintEvaluator",
    "Objective",
    "ObjectiveTerm",
    "ObjectiveAggregation",
    "Validator",
    "ValidatorResult",
    "Evidence",
    "Provenance",
    "ConfirmationState",
    "LifecycleState",
    "ModelBindingKind",
    "EXECUTABLE_MODEL_KINDS",
    "FOREIGN_MODEL_KINDS",
    "RelationType",
    "RELATION_TYPE_REF_PATTERN",
    "Quantity",
    "UnitRegistry",
    "DEFAULT_UNIT_REGISTRY",
    "normalize_unit",
    "units_compatible",
    # viz
    "to_mermaid",
    "to_dot",
    # document
    "TwinGraph",
    "SENTINEL_WORKSPACE",
    # compile
    "compile_graph",
    "CompileResult",
    "CompileReport",
    "ExecutablePlan",
    "ResolvedComponent",
    "CompiledConstraint",
    "ResolvedObjective",
    "QueryPlan",
    "ProgramCompatibilityReport",
    "COMPILER_VERSION",
    # composition
    "compose",
    "CompositionReport",
    "CompositionError",
    # program profiles
    "ProgramProfile",
    "ProfileRequirement",
    "ProgramRegistry",
    "InMemoryProgramRegistry",
    "BUILTIN_PROGRAM_REGISTRY",
    # registry
    "TypeRegistry",
    "ModelRegistry",
    "InMemoryTypeRegistry",
    "BUILTIN_TYPE_REGISTRY",
    "RELATION_TYPE_PACK",
    "POWER_TYPE_PACK",
    "DATA_CENTER_TYPE_PACK",
    "OPERATIONS_TYPE_PACK",
    "DATA_TYPE_PACK",
    "PLATFORM_ANALYSIS_TYPE_PACK",
    "BUILTIN_TYPE_PACKS",
    "register_type_pack",
    "build_type_registry",
    "TypeDef",
    "TypePack",
    "PropSpec",
    "VarSpec",
    "ActionSpec",
    "IOContract",
    "ModelSpec",
    # patch
    "SemanticPatch",
    "Operation",
    "PatchStatus",
    "apply_patch",
    "PatchApplyReport",
    "PatchLog",
    "lineage",
    # ids
    "new_ulid",
    "validate_ulid",
    "Ulid",
    # errors
    "Diagnostic",
    "CODES",
    "TwinGraphError",
    "UnknownTypeRefError",
    "UnknownModelRefError",
    "OutOfOrderPatchError",
    "ImmutableGraphError",
    "FrozenGraphError",
]
